"""rename column

Revision ID: 388ef81ef213
Revises: 
Create Date: 2022-03-22 15:33:19.417369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388ef81ef213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name', new_column_name='title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'title', new_column_name='name')
    # ### end Alembic commands ###
